=== AndresHerrera/TableroVuelosXML/aeropuerto.dtd
<!ELEMENT aeropuerto (nombre, vuelos, fecha)>
   <!ELEMENT nombre (#PCDATA)>
   <!ELEMENT vuelos (vuelo+)>
   <!ELEMENT vuelo (diario?, origen, destino, horasalida, horallegada)>
      <!ATTLIST vuelo codigo ID #REQUIRED>
      <!ATTLIST vuelo estado (C|A|R) "A">
   <!ELEMENT diario EMPTY>
   <!ELEMENT origen (#PCDATA)>
   <!ELEMENT destino (#PCDATA)>
   <!ELEMENT horasalida (#PCDATA)>
   <!ELEMENT horallegada (#PCDATA)>
   <!ELEMENT fecha (#PCDATA)>

=== AndresHerrera/TableroVuelosXML/vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuerto SYSTEM "aeropuerto.dtd">
<aeropuerto>
   <nombre>CLO</nombre>
   <vuelos>
      <vuelo codigo="CM806" estado="R">
         <diario />
         <origen>Cali</origen>
         <destino>Bogota</destino>
         <horasalida>6:30</horasalida>
         <horallegada>7:10</horallegada>
      </vuelo>
      <vuelo codigo="AV3483" estado="C">
         <origen>Cali</origen>
         <destino>Barranquilla</destino>
         <horasalida>10:15</horasalida>
         <horallegada>11:15</horallegada>
      </vuelo>
	  <vuelo codigo="AV9453" estado="A">
         <origen>Cali</origen>
         <destino>Miami</destino>
         <horasalida>5:45</horasalida>
         <horallegada>10:55</horallegada>
      </vuelo>
   </vuelos>
   <fecha>17/02/2018</fecha>
</aeropuerto>
